# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170624_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=300, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=80, verbose_name='校名'),
        ),
    ]
