# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20170624_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='校区')),
                ('address', models.CharField(max_length=300, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '校区',
                'verbose_name': '校区',
            },
        ),
    ]
