# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20170701_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='背景'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='标志'),
        ),
    ]
