# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20170701_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.AlterField(
            model_name='school',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='背景'),
        ),
    ]
