# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('people', models.CharField(max_length=80, verbose_name='People')),
                ('school', models.CharField(max_length=200, verbose_name='School')),
                ('home_address', models.CharField(max_length=200, verbose_name='Home Address')),
                ('mother_name', models.CharField(max_length=80, verbose_name='Mother Name')),
                ('mother_work', models.CharField(max_length=200, verbose_name='Mother Work')),
                ('father_name', models.CharField(max_length=80, verbose_name='Father Name')),
                ('father_work', models.CharField(max_length=200, verbose_name='Father Work')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('class_name', models.CharField(max_length=80, verbose_name='Class')),
                ('skill_level', models.CharField(max_length=80, verbose_name='Skill Level')),
                ('wechat', models.CharField(max_length=80, verbose_name='Wechat')),
                ('qq', models.CharField(max_length=80, verbose_name='QQ')),
                ('matric_date', models.DateField(verbose_name='Matric Date')),
                ('remarks', models.CharField(max_length=300, verbose_name='Remarks')),
            ],
        ),
    ]
