# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=80, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(verbose_name='毕业日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=80, verbose_name='父亲姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_work',
            field=models.CharField(max_length=200, verbose_name='父亲工作单位'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.CharField(max_length=200, verbose_name='家庭地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_date',
            field=models.DateField(verbose_name='入学日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=80, verbose_name='母亲姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_work',
            field=models.CharField(max_length=200, verbose_name='母亲工作单位'),
        ),
        migrations.AlterField(
            model_name='student',
            name='people',
            field=models.CharField(max_length=80, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=models.CharField(max_length=300, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=200, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_level',
            field=models.CharField(max_length=80, verbose_name='能力水平'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(verbose_name='入学日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wechat',
            field=models.CharField(max_length=80, verbose_name='微信'),
        ),
    ]
