# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170606_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生'},
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=80, verbose_name='姓名'),
        ),
    ]
