# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20170606_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(verbose_name='开始日期'),
        ),
    ]
