# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_district'),
        ('student', '0005_auto_20170624_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.District'),
            preserve_default=False,
        ),
    ]
