# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20170701_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.District', verbose_name='校区'),
        ),
    ]
