# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20170701_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='autumn_suite',
            field=models.BooleanField(default=False, verbose_name='领取冬装'),
        ),
        migrations.AddField(
            model_name='student',
            name='shoes',
            field=models.BooleanField(default=False, verbose_name='领取鞋子'),
        ),
        migrations.AddField(
            model_name='student',
            name='summer_suite',
            field=models.BooleanField(default=False, verbose_name='领取夏装'),
        ),
    ]
