# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20170702_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='autumn_suite',
            field=models.BooleanField(default=False, verbose_name='领取秋装'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, default='', null=True, verbose_name='生日'),
        ),
    ]
