# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20170704_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='入学日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='开始日期'),
        ),
    ]
